services:
  # Application service
  farm:
    build:
      context: ./server/
      dockerfile: Dockerfile
    image: ghcr.io/ilyastar9999/moded_distructive_farm:latest
    environment:
      - DB_PORT=5432
      - DB_HOST=postgres
      - DB_USER=farm
      - DB_PASS=asdasdasd
      - DB_NAME=farmdb
      - BOARD_URL=${BOARD_URL}
      - TEAM_TOKEN=${TEAM_TOKEN}
      - WEB_PASSWORD=${WEB_PASSWORD}
      - NUM_TEAMS=${NUM_TEAMS}
      - IP_TEAM_BASE=${IP_TEAM_BASE}
    depends_on:
      postgres:
        condition: service_healthy
    restart: "always"
    ports:
      -  "3333:8000"

  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: farm
      POSTGRES_PASSWORD: asdasdasd
      POSTGRES_DB: farmdb
    healthcheck:
      test: pg_isready -U farm -d farmdb
      interval: 10s
      timeout: 3s
      retries: 3
